apiVersion: v1
kind: Service
metadata:
  name: mysql-homework-mysql
  namespace: homework
  labels:
    app: mysql
    mysql: homework-mysql
spec:
  selector:
    app: mysql-homework-mysql
  ports:
    - port: 3306
      targetPort: 3306
