apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bucket-pvc
  namespace: homework
spec:
  storageClassName: rustfs-sc
  accessModes:
    # - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
