global:
  enabled: true
  tlsDisable: true

injector:
  enabled: false

server:
  enabled: true

  dataStorage:
    enabled: false

  auditStorage:
    enabled: false

  readinessProbe:
    enabled: false

  livenessProbe:
    enabled: false

  ha:
    enabled: true
    replicas: 3

    raft:
      enabled: false

    config: |
      ui = true

      listener "tcp" {
        address         = "0.0.0.0:8200"
        cluster_address = "0.0.0.0:8201"
        tls_disable     = true
      }

      storage "consul" {
        address = "consul-server.consul.svc.cluster.local:8500"
        path    = "vault/"
      }

      disable_mlock = true

  service:
    enabled: true
    type: ClusterIP

  ui:
    enabled: true
